#!/bin/bash

# Purge build
rm -fr build

# Build tools for build)
mkdir -p build
# gcc tools/makeheaders.c -o build/makeheaders
v -v -cg -shared -reuse-tmpc torri.v -o build/libtorri
# build/makeheaders -h /tmp/v/torri.tmp.so.c >build/torri.h
cp /tmp/v/torri.tmp.so.c build/torri.sample.h
python3 setup.py bdist_wheel
